
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    scan_interval: 5
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"

switch:
  - platform: remote_rpi_gpio
    host: pi
    ports:
      17: RPi Fan

panel_iframe:
  portainer:
    title: Portainer
    url: "http://portainer.pi:8999/#!/2/docker/containers"
    icon: mdi:docker
    require_admin: true
  nodered:
    title: Node-RED
    url: "http://nodered.pi:1880"
    icon: mdi:lan
    require_admin: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 3

alexa:
  smart_home:
    locale: en-US
    endpoint: https://api.amazonalexa.com/v3/events

